### ISSUE TITLE
Did you leave your backpack in a Miles car?

### ISSUE THREAD

**Issue by iamraffe** [srcnuzn/wizfi-iot#24]
I found a backpack in a miles car, dunno if it might be yours. Trying to find the owner

**Comment by srcnuzn** [comment]
Yes I'm the owner. Black hackathon backpack. Please contact me via mail srcnuzn4692373729@outlook.de

**Comment by iamraffe** [comment]
Done

**Comment by srcnuzn** [comment]
@iamraffe it seems you did not receive my mails. Did you check your spam?
